import {View, Text, StyleSheet, FlatList, Image, ActivityIndicator} from 'react-native';
import React, {useEffect, useState} from 'react';

const categoryProduct = [
  {
    asin: 'B0CWXNS552',
    product_title: 'Apple AirTag',
    product_price: '$23.99',
    product_original_price: '$29.00',
    currency: 'USD',
    product_star_rating: '4.6',
    product_num_ratings: 3439,
    product_url: 'https://www.amazon.com/dp/B0CWXNS552',
    product_photo:
      'https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 4,
    product_minimum_offer_price: '$22.07',
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: '1649374186',
    product_title: 'Onyx Storm (Deluxe Limited Edition) (The Empyrean, 3)',
    product_price: '$19.78',
    product_original_price: '$32.99',
    currency: 'USD',
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: 'https://www.amazon.com/dp/1649374186',
    product_photo:
      'https://m.media-amazon.com/images/I/9101MLPcFTL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$19.78',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'List: ',
    delivery:
      'FREE delivery on $35 shipped by Amazon.This title will be released on January 21, 2025.',
    has_variations: false,
  },
  {
    asin: 'B0D92TH7MV',
    product_title:
      'Keep It Simple Y&#x27;all: Easy dinners from Your Barefoot Neighbor',
    product_price: '$24.74',
    product_original_price: '$27.49',
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 292,
    product_url: 'https://www.amazon.com/dp/B0D92TH7MV',
    product_photo:
      'https://m.media-amazon.com/images/I/61Zk8idxPKL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 2,
    product_minimum_offer_price: '$20.49',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: 'List: ',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0CRCWCGNW',
    product_title:
      'Amazon Basics - Washable School Glue Sticks, Dries Clear, 2-Pack, Purple',
    product_price: '$0.25',
    unit_price: '$0.59',
    unit_count: 0,
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 7950,
    product_url: 'https://www.amazon.com/dp/B0CRCWCGNW',
    product_photo:
      'https://m.media-amazon.com/images/I/713QRmQtrcL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.25',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0D5FZGY8W',
    product_title:
      'URO Vaginal Probiotics for Women pH Balance with Prebiotics &amp; Lactobacillus Probiotic Blend - Women&#x27;s Vaginal Health Supplement - Promote Healthy Vaginal Odor &amp; Vaginal Flora, 60 Count (Pack of 1)',
    product_price: '$28.79',
    unit_price: '$0.48',
    unit_count: 60,
    product_original_price: '$31.99',
    currency: 'USD',
    product_star_rating: '4.5',
    product_num_ratings: 819,
    product_url: 'https://www.amazon.com/dp/B0D5FZGY8W',
    product_photo:
      'https://m.media-amazon.com/images/I/61tYAHJi3LL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 2,
    product_minimum_offer_price: '$28.50',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '100K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0D1XD1ZV3',
    product_title:
      'Apple AirPods Pro (2nd Generation) Wireless Ear Buds with USB-C Charging, Up to 2X More Active Noise Cancelling Bluetooth Headphones, Transparency Mode, Adaptive Audio, Personalized Spatial Audio',
    product_price: '$199.00',
    product_original_price: '$249.00',
    currency: 'USD',
    product_star_rating: '4.6',
    product_num_ratings: 1895,
    product_url: 'https://www.amazon.com/dp/B0D1XD1ZV3',
    product_photo:
      'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 4,
    product_minimum_offer_price: '$197.01',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery: 'FREE delivery Mon, Jul 29 Or fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0D4DJ6BRR',
    product_title:
      'DAYBETTER LED Strip Lights 130ft (2 Rolls of 65.6ft), Color Changing Lights Strip for Bedroom, Desk, Indoor, Room Bedroom, Girl Boy Brithday Gifts RGB Decor with Remote and 24V Power Supply',
    product_price: '$12.99',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.5',
    product_num_ratings: 27578,
    product_url: 'https://www.amazon.com/dp/B0D4DJ6BRR',
    product_photo:
      'https://m.media-amazon.com/images/I/813vxzjiChL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$12.99',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0CRDYZVDC',
    product_title:
      'Amazon Basics Heavy Duty Plastic Folders with 2 Pockets for Letter Size Paper, Red and Blue, 2-Pack',
    product_price: '$0.49',
    unit_price: '$0.25',
    unit_count: 2,
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 13581,
    product_url: 'https://www.amazon.com/dp/B0CRDYZVDC',
    product_photo:
      'https://m.media-amazon.com/images/I/61aub4rRv9L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.49',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0CT2R7199',
    product_title:
      'HP DeskJet 2855e Wireless All-in-One Color Inkjet Printer, Scanner, Copier, Best-for-home, 3 months of ink included (588S5A)',
    product_price: '$49.99',
    product_original_price: '$84.99',
    currency: 'USD',
    product_star_rating: '4',
    product_num_ratings: 47607,
    product_url: 'https://www.amazon.com/dp/B0CT2R7199',
    product_photo:
      'https://m.media-amazon.com/images/I/61+biEwB1hL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 12,
    product_minimum_offer_price: '$47.99',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '80K+ bought in past month',
    delivery: 'FREE delivery Mon, Jul 29',
    has_variations: false,
  },
  {
    asin: 'B0D3RJP3G2',
    product_title: 'Twisters: The Album',
    product_price: '$12.97',
    product_original_price: '$18.98',
    currency: 'USD',
    product_star_rating: '5',
    product_num_ratings: 3,
    product_url: 'https://www.amazon.com/dp/B0D3RJP3G2',
    product_photo:
      'https://m.media-amazon.com/images/I/71GPcFCND9L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$12.97',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '1K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0CRD97QJ3',
    product_title:
      'Amazon Basics Washable Liquid School Glue, 5 fl.oz Bottle, 147ml,1-Pack, Clear',
    product_price: '$0.25',
    unit_price: '$0.05',
    unit_count: 5,
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 615,
    product_url: 'https://www.amazon.com/dp/B0CRD97QJ3',
    product_photo:
      'https://m.media-amazon.com/images/I/61VKzti3gKL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.25',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B07RFSSYBH',
    product_title:
      'Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones',
    product_price: '$0.00',
    product_original_price: '$18.00',
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 130130,
    product_url: 'https://www.amazon.com/dp/B07RFSSYBH',
    product_photo:
      'https://m.media-amazon.com/images/I/71F4+7rk2eL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Other formats: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0C9N2L56X',
    product_title:
      'The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness',
    product_price: '$0.00',
    product_original_price: '$20.25',
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 2144,
    product_url: 'https://www.amazon.com/dp/B0C9N2L56X',
    product_photo:
      'https://m.media-amazon.com/images/I/81N4drWaxuL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Other formats: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0CPWYVX6H',
    product_title: 'Energizer 2450 Lithium Coin Battery, 2 Pack',
    product_price: '$5.42',
    unit_price: '$2.71',
    unit_count: 2,
    product_original_price: '$8.98',
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 1584,
    product_url: 'https://www.amazon.com/dp/B0CPWYVX6H',
    product_photo:
      'https://m.media-amazon.com/images/I/71LSsuHdVBL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$5.42',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: '3K+ bought in past month',
    delivery: 'FREE delivery Thu, Aug 1 Or fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0CV4FQPY1',
    product_title:
      'Bounty Select-A-Size Paper Towels, White, 8 Triple Rolls = 24 Regular Rolls',
    product_price: '$22.18',
    unit_price: '$2.05',
    unit_count: 11,
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 36595,
    product_url: 'https://www.amazon.com/dp/B0CV4FQPY1',
    product_photo:
      'https://m.media-amazon.com/images/I/81jYzN4cAdL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$22.18',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '60K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: '0062300555',
    product_title:
      'Hillbilly Elegy: A Memoir of a Family and Culture in Crisis',
    product_price: '$9.40',
    product_original_price: '$18.99',
    currency: 'USD',
    product_star_rating: '4.3',
    product_num_ratings: 97683,
    product_url: 'https://www.amazon.com/dp/0062300555',
    product_photo:
      'https://m.media-amazon.com/images/I/81ytGlIkLoL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$9.40',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'List: ',
    delivery: 'FREE delivery on $35 shipped by Amazon.',
    has_variations: false,
  },
  {
    asin: 'B0CL72PR7B',
    product_title: 'A Death in Cornwall: A Novel (Gabriel Allon Book 24)',
    product_price: '$15.99',
    product_original_price: '$32.00',
    currency: 'USD',
    product_star_rating: '4.6',
    product_num_ratings: 4565,
    product_url: 'https://www.amazon.com/dp/B0CL72PR7B',
    product_photo:
      'https://m.media-amazon.com/images/I/81KoDl1nhVL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$15.99',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Print List Price: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0D7ZPCB25',
    product_title: 'Teacher Simulator: School Days',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '3.7',
    product_num_ratings: 4,
    product_url: 'https://www.amazon.com/dp/B0D7ZPCB25',
    product_photo:
      'https://m.media-amazon.com/images/I/51ZPA+MZGgL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Jun 26, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0D2PKQGQV',
    product_title:
      'Hanes Men&#x27;s Pocket Undershirt Pack, Cotton Crew Neck T-Shirt, Moisture Wicking Tee, Assorted 6-Pack',
    product_price: '$22.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.4',
    product_num_ratings: 25110,
    product_url: 'https://www.amazon.com/dp/B0D2PKQGQV',
    product_photo:
      'https://m.media-amazon.com/images/I/81v4ewQrCgL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$22.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '1K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: true,
  },
  {
    asin: 'B09MVCQJBJ',
    product_title: 'Xbox',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.2',
    product_num_ratings: 104,
    product_url: 'https://www.amazon.com/dp/B09MVCQJBJ',
    product_photo:
      'https://m.media-amazon.com/images/I/41amEfnVeyL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Jul 8, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0D3RDF55W',
    product_title: 'Louis In London',
    product_price: '$13.98',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '5',
    product_num_ratings: 2,
    product_url: 'https://www.amazon.com/dp/B0D3RDF55W',
    product_photo:
      'https://m.media-amazon.com/images/I/71A0zrZRG1L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$13.98',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: '900+ bought in past month',
    delivery:
      'FREE delivery Tue, Jul 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0CP93N5S2',
    product_title: 'All the Colors of the Dark',
    product_price: '$13.99',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.6',
    product_num_ratings: 4243,
    product_url: 'https://www.amazon.com/dp/B0CP93N5S2',
    product_photo:
      'https://m.media-amazon.com/images/I/81RBcyIyl2L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$13.99',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Other formats: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0D68R2D7R',
    product_title:
      'POPPI Sparkling Prebiotic Soda, Beverages w/Apple Cider Vinegar, Seltzer Water &amp; Fruit Juice, NEW Crowd Pleasers, 12 oz (12 Pack)',
    product_price: '$29.99',
    unit_price: '$0.21',
    unit_count: 143,
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.3',
    product_num_ratings: 28206,
    product_url: 'https://www.amazon.com/dp/B0D68R2D7R',
    product_photo:
      'https://m.media-amazon.com/images/I/71fHyCScsCL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$29.99',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: '30K+ bought in past month',
    delivery: 'FREE delivery on $35 shipped by Amazon.',
    has_variations: false,
  },
  {
    asin: 'B0D73NMM7N',
    product_title: 'Fluvsies Merge Party',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.3',
    product_num_ratings: 9,
    product_url: 'https://www.amazon.com/dp/B0D73NMM7N',
    product_photo:
      'https://m.media-amazon.com/images/I/81k3RzdCdxL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Jun 27, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0D679Y1WX',
    product_title: 'Passage Du Desir',
    product_price: '$12.98',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 8,
    product_url: 'https://www.amazon.com/dp/B0D679Y1WX',
    product_photo:
      'https://m.media-amazon.com/images/I/9182719TpgL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 18,
    product_minimum_offer_price: '$11.96',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: '1K+ bought in past month',
    delivery: 'FREE delivery on $35 shipped by Amazon.',
    has_variations: false,
  },
  {
    asin: 'B0D8C3TVH1',
    product_title: 'Like a Prayer Silver Collection',
    product_price: '$24.98',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.9',
    product_num_ratings: 9,
    product_url: 'https://www.amazon.com/dp/B0D8C3TVH1',
    product_photo:
      'https://m.media-amazon.com/images/I/71Y-AGGxjhL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$24.98',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '200+ bought in past month',
    delivery:
      'FREE delivery Tue, Sep 10 on $35 of items shipped by AmazonOr fastest delivery Fri, Sep 6 This title will be released on September 6, 2024.',
    has_variations: false,
  },
  {
    asin: 'B0D7KR99VL',
    product_title: 'Get unlimited Free Robux 2024',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '1.8',
    product_num_ratings: 5,
    product_url: 'https://www.amazon.com/dp/B0D7KR99VL',
    product_photo:
      'https://m.media-amazon.com/images/I/71H3ahAWJHL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Jun 20, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0D8N8S6SH',
    product_title: 'Maxxxine 4K + Bluray + Digital [4K UHD]',
    product_price: '$24.78',
    product_original_price: '$42.99',
    currency: 'USD',
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: 'https://www.amazon.com/dp/B0D8N8S6SH',
    product_photo:
      'https://m.media-amazon.com/images/I/81VaPt1UEeL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$24.78',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: '1K+ bought in past month',
    delivery:
      'FREE delivery on $35 shipped by Amazon.This title has not yet been released.',
    has_variations: false,
  },
  {
    asin: '1728296161',
    product_title: 'Never Lie',
    product_price: '$8.11',
    product_original_price: '$17.99',
    currency: 'USD',
    product_star_rating: '4.4',
    product_num_ratings: 172553,
    product_url: 'https://www.amazon.com/dp/1728296161',
    product_photo:
      'https://m.media-amazon.com/images/I/81PIs7jhL0L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 34,
    product_minimum_offer_price: '$5.14',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: 'List: ',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B00OZP5VRS',
    product_title: 'A Court of Thorns and Roses',
    product_price: '$8.21',
    product_original_price: '$15.20',
    currency: 'USD',
    product_star_rating: '4.6',
    product_num_ratings: 220371,
    product_url: 'https://www.amazon.com/dp/B00OZP5VRS',
    product_photo:
      'https://m.media-amazon.com/images/I/81A-T+X6ukL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$8.21',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Digital List Price: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0CL1YQLB5',
    product_title: 'The God of the Woods: A Novel',
    product_price: '$14.99',
    product_original_price: '$30.00',
    currency: 'USD',
    product_star_rating: '4.5',
    product_num_ratings: 1765,
    product_url: 'https://www.amazon.com/dp/B0CL1YQLB5',
    product_photo:
      'https://m.media-amazon.com/images/I/81WrOo6+IQL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$14.99',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Print List Price: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B01GGU0XWC',
    product_title: 'It Ends with Us',
    product_price: '$0.00',
    product_original_price: '$20.24',
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 330109,
    product_url: 'https://www.amazon.com/dp/B01GGU0XWC',
    product_photo:
      'https://m.media-amazon.com/images/I/815GWEqlkOL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Other formats: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0CPV6S3D7',
    product_title: 'The Black Bird Oracle: A Novel (All Souls Series Book 5)',
    product_price: '$13.99',
    product_original_price: '$32.00',
    currency: 'USD',
    product_star_rating: '4.6',
    product_num_ratings: 1301,
    product_url: 'https://www.amazon.com/dp/B0CPV6S3D7',
    product_photo:
      'https://m.media-amazon.com/images/I/81kOz-i2QBL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$13.99',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Print List Price: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0CTD3M2HD',
    product_title:
      'Kleenex Ultra Soft Facial Tissues, 8 Flat Boxes, 180 Tissues per Box, 3-Ply, Packaging May Vary',
    product_price: '$25.49',
    unit_price: '$1.77',
    unit_count: 14,
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 48053,
    product_url: 'https://www.amazon.com/dp/B0CTD3M2HD',
    product_photo:
      'https://m.media-amazon.com/images/I/71H5-vQdkzL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 3,
    product_minimum_offer_price: '$24.47',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: '40K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 25',
    coupon_text: 'Save $2.00 with coupon',
    has_variations: false,
  },
  {
    asin: 'B0D627TNMQ',
    product_title: 'MTV Unplugged',
    product_price: '$34.98',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 395,
    product_url: 'https://www.amazon.com/dp/B0D627TNMQ',
    product_photo:
      'https://m.media-amazon.com/images/I/91dIJLfxyYL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$34.98',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '100+ bought in past month',
    delivery:
      'FREE delivery Tue, Sep 10 on $35 of items shipped by AmazonOr fastest delivery Fri, Sep 6 This title will be released on September 6, 2024.',
    has_variations: false,
  },
  {
    asin: '1538742578',
    product_title: 'The Housemaid',
    product_price: '$6.96',
    product_original_price: '$12.99',
    currency: 'USD',
    product_star_rating: '4.5',
    product_num_ratings: 331276,
    product_url: 'https://www.amazon.com/dp/1538742578',
    product_photo:
      'https://m.media-amazon.com/images/I/81AHTyq2wVL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 48,
    product_minimum_offer_price: '$3.71',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: 'List: ',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0C4QD5VPB',
    product_title: 'The Women: A Novel',
    product_price: '$0.00',
    product_original_price: '$24.74',
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 147949,
    product_url: 'https://www.amazon.com/dp/B0C4QD5VPB',
    product_photo:
      'https://m.media-amazon.com/images/I/91mP3553EzL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Other formats: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0D8WNC617',
    product_title: 'Battle Clash Baseball 9',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '1',
    product_num_ratings: 1,
    product_url: 'https://www.amazon.com/dp/B0D8WNC617',
    product_photo:
      'https://m.media-amazon.com/images/I/812lAbPVe4L._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Jul 5, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: '0349132615',
    product_title: 'The Housemaid&#x27;s Secret',
    product_price: '$7.68',
    product_original_price: '$12.99',
    currency: 'USD',
    product_star_rating: '4.4',
    product_num_ratings: 176776,
    product_url: 'https://www.amazon.com/dp/0349132615',
    product_photo:
      'https://m.media-amazon.com/images/I/81LZXcfKqJL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 38,
    product_minimum_offer_price: '$4.91',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: 'List: ',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0C9QWV9K2',
    product_title: 'Adobe Acrobat Reader: Edit PDF',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '2.7',
    product_num_ratings: 4,
    product_url: 'https://www.amazon.com/dp/B0C9QWV9K2',
    product_photo:
      'https://m.media-amazon.com/images/I/41Wt+LyfovL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Oct 25, 2023',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0CZ7NKH1T',
    product_title: 'Triviascapes: relaxing trivia &amp; IQ quiz',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.3',
    product_num_ratings: 36,
    product_url: 'https://www.amazon.com/dp/B0CZ7NKH1T',
    product_photo:
      'https://m.media-amazon.com/images/I/71DhfojGRZL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Apr 10, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0CKNM2RS7',
    product_title: 'Eruption',
    product_price: '$0.00',
    product_original_price: '$21.83',
    currency: 'USD',
    product_star_rating: '4.3',
    product_num_ratings: 14297,
    product_url: 'https://www.amazon.com/dp/B0CKNM2RS7',
    product_photo:
      'https://m.media-amazon.com/images/I/91jZ4396SPL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Other formats: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
  {
    asin: 'B0D1WXVQTN',
    product_title:
      'Apple AirPods (3rd Generation) Wireless Ear Buds, Bluetooth Headphones, Personalized Spatial Audio, Sweat and Water Resistant, Lightning Charging Case Included, Up to 30 Hours of Battery Life',
    product_price: '$169.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.2',
    product_num_ratings: 693,
    product_url: 'https://www.amazon.com/dp/B0D1WXVQTN',
    product_photo:
      'https://m.media-amazon.com/images/I/61df2M5+OnL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 3,
    product_minimum_offer_price: '$114.46',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '10K+ bought in past month',
    delivery: 'FREE delivery Mon, Jul 29 Or fastest delivery Fri, Jul 26',
    has_variations: false,
  },
  {
    asin: 'B0D812Z2T1',
    product_title:
      'NUBWO G08 Dual Wireless Gaming Headset with Mic for PS5, PS4, PC, Mobile &amp; Tablet | 2.4GHz Wireless &amp; Bluetooth 5.3 | 100 Hr Battery | 50mm Drivers | Lightweight &amp; RGB Lighting - Blue',
    product_price: '$29.99',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '4.7',
    product_num_ratings: 40,
    product_url: 'https://www.amazon.com/dp/B0D812Z2T1',
    product_photo:
      'https://m.media-amazon.com/images/I/61ewRM2av0L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 2,
    product_minimum_offer_price: '$29.10',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '300+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    coupon_text: 'Save 50% with coupon',
    has_variations: false,
  },
  {
    asin: 'B0CT67D4JH',
    product_title:
      'Scott Paper Towels, Choose-A-Sheet, 30 Double Rolls (2 Packs of 15) = 60 Regular Rolls (100 Sheets Per Roll)',
    product_price: '$31.10',
    unit_price: '$1.04',
    unit_count: 30,
    product_original_price: '$32.98',
    currency: 'USD',
    product_star_rating: '4.5',
    product_num_ratings: 11234,
    product_url: 'https://www.amazon.com/dp/B0CT67D4JH',
    product_photo:
      'https://m.media-amazon.com/images/I/812-y3MIhmL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 2,
    product_minimum_offer_price: '$30.79',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: '30K+ bought in past month',
    delivery:
      'FREE delivery Mon, Jul 29 on $35 of items shipped by AmazonOr fastest delivery Fri, Jul 26',
    coupon_text: 'Extra 20% off when you subscribe',
    has_variations: false,
  },
  {
    asin: 'B0CW9YSDLL',
    product_title: 'ZEPETO: Avatar, Connect &amp; Play',
    product_price: '$0.00',
    product_original_price: null,
    currency: 'USD',
    product_star_rating: '1.3',
    product_num_ratings: 27,
    product_url: 'https://www.amazon.com/dp/B0CW9YSDLL',
    product_photo:
      'https://m.media-amazon.com/images/I/81v-IEtwbsL._AC_UL960_FMwebp_QL65_.png',
    product_num_offers: 1,
    product_minimum_offer_price: '$0.00',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'May 30, 2024',
    delivery: 'Available instantly on compatible devices',
    has_variations: false,
  },
  {
    asin: 'B0015259Z8',
    product_title: 'Crocs Unisex-Adult Classic Clogs',
    product_price: '$39.95',
    product_original_price: '$49.99',
    currency: 'USD',
    product_star_rating: '4.8',
    product_num_ratings: 582719,
    product_url: 'https://www.amazon.com/dp/B0015259Z8',
    product_photo:
      'https://m.media-amazon.com/images/I/61kuoM3sRaL._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$39.95',
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: '4K+ bought in past month',
    delivery: 'FREE delivery Tue, Jul 30 Or fastest delivery Fri, Jul 26',
    has_variations: true,
  },
  {
    asin: 'B0CLKQF5HR',
    product_title: 'Swan Song',
    product_price: '$14.99',
    product_original_price: '$30.00',
    currency: 'USD',
    product_star_rating: '4.5',
    product_num_ratings: 12546,
    product_url: 'https://www.amazon.com/dp/B0CLKQF5HR',
    product_photo:
      'https://m.media-amazon.com/images/I/71dSn3QCY6L._AC_UL960_FMwebp_QL65_.jpg',
    product_num_offers: 1,
    product_minimum_offer_price: '$14.99',
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: 'Print List Price: ',
    delivery: 'Available instantly',
    has_variations: false,
  },
];



export default function CategoryProduct() {

    const [products, setProducts] = useState(categoryProduct.slice(0, 10));
    const [page, setPage] = useState(1);
    const [isLoading, setIsLoading] = useState(false);
  
    const loadMoreProducts = () => {
      if (!isLoading) {
        setIsLoading(true);
        const newPage = page + 1;
        const newProducts = categoryProduct.slice(0, newPage * 10);
        setProducts(newProducts);
        setPage(newPage);
        setIsLoading(false);
      }
    };
  
    return (
      <View style={styles.container}>
        <FlatList
          data={products}
          keyExtractor={(item) => item.asin}
          renderItem={({ item }) => (
            <View style={styles.productCard}>
              <Image source={{ uri: item.product_photo }} style={styles.image} />
              <View style={styles.details}>
                <Text style={styles.title}>{item.product_title}</Text>
                <Text style={styles.price}>
                  {item.product_price}{' '}
                  <Text style={styles.originalPrice}>{item.product_original_price}</Text>
                </Text>
                <View style={styles.ratingContainer}>
                  <Text style={styles.rating}>⭐ {item.product_star_rating}</Text>
                  <Text style={styles.numRatings}>({item.product_num_ratings})</Text>
                </View>
                <Text style={styles.salesVolume}>{item.sales_volume}</Text>
                <Text style={styles.delivery}>{item.delivery}</Text>
                {item.is_amazon_choice && (
                  <Text style={ styles.tag}>Amazon's Choice</Text>
                )}
                {item.is_prime && <Text style={styles.tag}>Prime</Text>}
              </View>
            </View>
          )}
          onEndReached={loadMoreProducts}
          onEndReachedThreshold={0.5}
          ListFooterComponent={isLoading ? <ActivityIndicator size="large" color="#0000ff" /> : null}
        />
      </View>
    );
  }
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f4f4f4',
      padding: 10,
    },
    productCard: {
      flexDirection: 'row',
      backgroundColor: '#fff',
      alignItems:"center",
      borderRadius: 8,
      marginBottom: 10,
      padding: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 3,
    },
    image: {
      width: 100,
      height: 100,
      borderRadius: 8,
    },
    details: {
      flex: 1,
      marginLeft: 10,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
    },
    price: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#f68b1e',
      marginTop: 4,
    },
    originalPrice: {
      fontSize: 12,
      textDecorationLine: 'line-through',
      color: '#888',
      marginLeft: 5,
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    rating: {
      fontSize: 14,
      color: '#f68b1e',
    },
    numRatings: {
      fontSize: 12,
      color: '#666',
      marginLeft: 5,
    },
    salesVolume: {
      fontSize: 12,
      color: '#333',
      marginTop: 4,
    },
    delivery: {
      fontSize: 12,
      color: '#333',
      marginTop: 4,
    },
    tag: {
      fontSize: 12,
      color: '#fff',
      backgroundColor: '#0a84ff',
      borderRadius: 4,
      paddingHorizontal: 6,
      paddingVertical: 2,
      alignSelf: 'flex-start',
      marginTop: 4,
      marginRight: 4,
    },
  });